name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2 # 虚拟环境搭建go环境
      with:
        go-version: 1.16 #指定1.16版本
    
    - name: Build
      run: cd ./github-actions && go build -o main #在虚拟环境编译microblog应用
      
    - name: Test
      run: cd ./github-actions &&  go test ./hello
    
      # 将编译出的二进制文件 scp 到我们的服务器
    - name: SCP Files 
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}  # Secrets中的配置：IP地址
        username: ${{ secrets.DEPLOY_USER }}  # Secrets中的配置：登录用户名
        port: ${{ secrets.DEPLOY_PORT }} # Secrets中的配置：端口
        key: ${{ secrets.DEPLOY_KEY }} # Secrets中的配置：我们服务器上创建的ssh key的私钥内容
        source: 'main'  # 编译出的二进制文件名
        target: ${{ secrets.DEPLOY_PATH }} # Secrets中的配置：scp 到我们服务器上的的目录
